### ISSUE TITLE
ClipData NullPointerException

### ISSUE THREAD

**Issue by hendrawd** [woxingxiao/XEditText#31]
## Library version:
com.xw.repo:xedittext:2.0.5

## Device info
Galaxy Note4
Android version 6
1.03 GiB FREE SPACE
582.00 MiB FREE RAM

## Stacktrace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
       at com.xw.repo.XEditText.onTextContextMenuItem(XEditText.java:251)
       at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3666)
       at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:4234)
       at com.android.internal.view.FloatingActionMode$4.onMenuItemSelected(FloatingActionMode.java:108)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)
       at com.android.internal.view.FloatingActionMode$5.onMenuItemClick(FloatingActionMode.java:136)
       at com.android.internal.widget.FloatingToolbar$FloatingToolbarMainPanel$1.onClick(FloatingToolbar.java:1282)
       at android.view.View.performClick(View.java:5697)
       at android.widget.TextView.performClick(TextView.java:10826)
       at android.view.View$PerformClick.run(View.java:22526)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by hendrawd** [comment]
Might be related to https://github.com/woxingxiao/XEditText/issues/28
