### ISSUE TITLE
使用pattern时用粘贴IndexOutOfBoundsException

### ISSUE THREAD

**Issue by wmjwmj828** [woxingxiao/XEditText#32]
设置了app:x_pattern="3,4,4"
app:x_separator=" "
粘贴时， java.lang.IndexOutOfBoundsException: setSpan (17 ... 17) ends beyond length 12

**Comment by woxingxiao** [comment]
是最新版吗？

**Comment by wmjwmj828** [comment]
@woxingxiao 用的是最新版implementation 'com.xw.repo:xedittext:2.2.1@aar'，这个异常是必现的
W/System.err: java.lang.IndexOutOfBoundsException: setSpan (21 ... 21) ends beyond length 11
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
W/System.err:     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at android.widget.EditText.setSelection(EditText.java:103)
        at com.xw.repo.XEditText.setTextToSeparate(XEditText.java:540)
        at com.xw.repo.XEditText.setTextEx(XEditText.java:509)
        at com.xw.repo.XEditText.onTextContextMenuItem(XEditText.java:346)
        at android.widget.Editor$ActionPopupWindow.onClick(Editor.java:3945)
        at android.view.View.performClick(View.java:5656)
        at android.widget.TouchPanelLayout.resetChildState(TouchPanelLayout.java:58)
        at android.widget.TouchPanelLayout.dispatchTouchEvent(TouchPanelLayout.java:46)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)

**Comment by woxingxiao** [comment]
@wmjwmj828 
什么ROM，我周边的手机都正常。可以试试运行我的demo看看

**Comment by woxingxiao** [comment]
@wmjwmj828 已解决。

**Comment by wmjwmj828** [comment]
@woxingxiao 还是报IndexOutOfBoundsException啊。。我用了很多台手机都是必现，小米note3，华为荣耀9，vivo y85

 implementation 'com.xw.repo:xedittext:2.2.2@aar'

XEditText：
            <com.xw.repo.XEditText
                android:id="@+id/et_tel"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="34px"
                android:layout_marginLeft="40px"
                android:layout_marginRight="40px"
                android:layout_marginTop="34px"
                android:background="@null"
                android:inputType="number"
                android:textSize="36px"
                app:x_pattern="3,4,4"
                app:x_separator=" " />

**Comment by woxingxiao** [comment]
@wmjwmj828 
我怀疑你本地库没有刷新。你尝试注释 implementation 'com.xw.repo:xedittext:2.2.2@aar' 这一行->clean项目->解开注释->build

**Comment by wmjwmj828** [comment]
@woxingxiao 我clean build过了，还是报错
setTextToSeparate(XEditText.java:545) 已经跟上次报错的函数不一样了

W/System.err: java.lang.IndexOutOfBoundsException: setSpan (11 ... 11) ends beyond length 10
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at android.widget.EditText.setSelection(EditText.java:103)
        at com.xw.repo.XEditText.setTextToSeparate(XEditText.java:545)
        at com.xw.repo.XEditText.setTextEx(XEditText.java:513)
        at com.xw.repo.XEditText.onTextContextMenuItem(XEditText.java:349)

**Comment by woxingxiao** [comment]
这就非常奇怪了，我这里没有任何问题。你是怎么使用引发的异常，设置的内容是什么，你点进去看看本地XEditText的545行代码内容是什么

**Comment by woxingxiao** [comment]
分批粘贴操作太骚，我就是测一天也不会想到。。讲真，我在项目里使用这么久还从来没遇到一个用户会这样用。不过确实是个bug，将来有空再解决了。

**Comment by wmjwmj828** [comment]
测试就是这么骚.. 我现在是禁止黏贴了
